/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * manajemenData.java
 *
 * Created on 04 Jul 10, 15:50:24
 */

package seleksipegawai;

/**
 *
 * @author bLueZ
 */
public class manajemenData extends javax.swing.JFrame {

    int rowNum,colmNum;
    String [][] queryPendaftar;

    DBconn conn;

    /** Creates new form manajemenData */
    public manajemenData() {
        conn = new DBconn();
        initComponents();
        
        getDataFromDb();
        
        for(int x=0; x<queryPendaftar.length; x++){
            for(int y=0; y<queryPendaftar[x].length; y++){
            jTable1.setValueAt(queryPendaftar[x][y], x, y);

            }
        }

    }

    public void getSelectedCell(){
        rowNum = jTable1.getSelectedRow();
        colmNum = jTable1.getSelectedColumn();
    }

    public void setTextSelectedCell(int columnNumber, int rowNumber){

    }

    public void getDataFromDb(){
        queryPendaftar = conn.execQuery("select * from pendaftar");
    }

    public void saveEdit(){

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleksipegawaiPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("seleksipegawaiPU").createEntityManager();
        datatrainingQuery = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT d FROM Datatraining d");
        datatrainingList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : datatrainingQuery.getResultList();
        pendaftarQuery = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT p FROM Pendaftar p");
        pendaftarList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendaftarQuery.getResultList();
        pendaftarQuery1 = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT p FROM Pendaftar p");
        pendaftarList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendaftarQuery1.getResultList();
        pendaftarQuery2 = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT p FROM Pendaftar p");
        pendaftarList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendaftarQuery2.getResultList();
        pendaftarQuery3 = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT p FROM Pendaftar p");
        pendaftarList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendaftarQuery3.getResultList();
        pendaftarQuery4 = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT p FROM Pendaftar p");
        pendaftarList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendaftarQuery4.getResultList();
        pendaftarQuery5 = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT p FROM Pendaftar p");
        pendaftarList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendaftarQuery5.getResultList();
        pendaftarQuery6 = java.beans.Beans.isDesignTime() ? null : seleksipegawaiPUEntityManager.createQuery("SELECT p FROM Pendaftar p");
        pendaftarList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendaftarQuery6.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(seleksipegawai.SeleksiPegawaiApp.class).getContext().getResourceMap(manajemenData.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getSelectedCell();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manajemenData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<seleksipegawai.Datatraining> datatrainingList;
    private javax.persistence.Query datatrainingQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<seleksipegawai.Pendaftar> pendaftarList;
    private java.util.List<seleksipegawai.Pendaftar> pendaftarList1;
    private java.util.List<seleksipegawai.Pendaftar> pendaftarList2;
    private java.util.List<seleksipegawai.Pendaftar> pendaftarList3;
    private java.util.List<seleksipegawai.Pendaftar> pendaftarList4;
    private java.util.List<seleksipegawai.Pendaftar> pendaftarList5;
    private java.util.List<seleksipegawai.Pendaftar> pendaftarList6;
    private javax.persistence.Query pendaftarQuery;
    private javax.persistence.Query pendaftarQuery1;
    private javax.persistence.Query pendaftarQuery2;
    private javax.persistence.Query pendaftarQuery3;
    private javax.persistence.Query pendaftarQuery4;
    private javax.persistence.Query pendaftarQuery5;
    private javax.persistence.Query pendaftarQuery6;
    private javax.persistence.EntityManager seleksipegawaiPUEntityManager;
    // End of variables declaration//GEN-END:variables

}
